name = "startup-time-error"
compatibility_date = "2024-03-19"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGE1ZmI4NmYtZWUyOC00MWQzLWE4MjAtOGVkNTdmZDAxOTBjIiwidGVuYW50X2lkIjoiZmY5YjJlOGZlMDEzMzE1MjgwNjlmZTQzZWM5NWRhYzAyMjJlMWEyMzcwMTE2MDU3ZTY4MTIxMzVmYmQxMjMyOSIsImludGVybmFsX3NlY3JldCI6ImQ4ZGExNjE1LTYwN2EtNGRlNy1hNzU2LTM2YmVjODE0NWQ5NiJ9.U7GZLEKQjHv9R1IJuU0UAVKjt01TIYj29a2tFVofDZs"
